"use strict";
let csrf = "", current = null, handoffText = "";
const $ = id => document.getElementById(id);
const esc = x => String(x ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const labels = {SPEC:"需求规格",PLAN:"检索计划",RETRIEVE:"官网采集",NORMALIZE:"号码规范",FILTER:"字段筛选",MATCH:"全文取证",GAP:"补检补证",REVIEW:"独立复核",EXPORT:"结果交付"};
const statuses = {WAITING_AGENT:"等待 Agent 处理",WAITING_IMPORT:"等待导入材料",WAITING_HUMAN:"等待人工确认",READY_EXPORT:"可导出",DONE:"已交付",RUNNING:"处理中"};
function message(text, error=false){$("message").textContent=text;$("message").className=error?"error":"";$("message").hidden=false;}
async function api(action, data={}){const response=await fetch("/api/action",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({action,run_id:current?.run_id,...data})});const body=await response.json();if(!response.ok)throw Error(body.error||"操作失败");return body;}
async function perform(fn){try{await fn();}catch(error){message(error.message,true);}}
async function loadList(){const list=await(await fetch("/api/runs")).json();$("runs").innerHTML=list.map(r=>`<button data-run="${esc(r.run_id)}" class="${r.run_id===current?.run_id?'selected':''}">${esc(r.title)}<small>${esc(labels[r.stage])} · ${esc(statuses[r.status]||r.status)}</small></button>`).join("")||'<p class="muted">还没有任务</p>';document.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>perform(()=>loadRun(b.dataset.run)));}
async function loadRun(id){const response=await fetch("/api/run?id="+encodeURIComponent(id));const body=await response.json();if(!response.ok)throw Error(body.error);current=body;renderRun();await loadList();}
function renderRun(){const r=current;$("create-view").hidden=true;$("run-view").hidden=false;$("page-title").textContent=r.title;$("status").textContent=statuses[r.status]||r.status;$("run-id").textContent=r.run_id;const steps=["SPEC","PLAN","RETRIEVE","FILTER","MATCH","GAP","REVIEW","EXPORT"];const position=steps.indexOf(r.stage);$("steps").innerHTML=steps.map((s,i)=>`<span class="${i===position?'current':i<position?'past':''}">${labels[s]}</span>`).join("");
let next=r.status==="WAITING_AGENT"?[`请让 Codex 完成${labels[r.stage]}`,"点击下方“生成 Agent 任务”，将指令复制到 Codex 聊天。"]:r.status==="WAITING_IMPORT"?["请补充检索结果或 PDF",r.pending_evidence.length?"到“候选与 PDF”放入缺少的材料，确认完整性后继续。":"在智慧芽普通专家搜索执行检索式，导出结果后登记实际检索式、总数和执行状态。"]:r.status==="WAITING_HUMAN"?[r.stage==="SPEC"?"请确认检索规格":"请抽检并确认交付",r.stage==="SPEC"?"到“条件与记录”检查必须满足的条件，再填写确认人。":"检查候选文献与证据后，填写确认人并点击“已抽检，确认导出”。"]:r.status==="DONE"?["本次结果已交付",`输出状态：${r.last_export?.status||""}。报告保存在当前任务文件夹。`]:["已准备好交付","点击右上方“导出结果”。"];
$("next-action").innerHTML=`<strong>${esc(next[0])}</strong><p>${esc(next[1])}</p>`+(r.status==="DONE"?`<p><a class="link" href="/report/${encodeURIComponent(r.run_id)}" target="_blank" rel="noopener">打开检索报告 →</a></p>`:"");
const values=Object.values(r.results), count=label=>values.filter(v=>v.class===label).length;$("stats").innerHTML=[[Object.keys(r.records).length,"候选文献"],[count("匹配"),"拟匹配 · 需独立复核"],[count("排除"),"排除"],[count("待核实"),"待核实"]].map(([n,l])=>`<div class="stat"><b>${n}</b><span>${l}</span></div>`).join("");
$("packet").disabled=r.status!=="WAITING_AGENT";$("export").disabled=!["READY_EXPORT","DONE"].includes(r.status);$("confirm-spec").disabled=!(r.stage==="SPEC"&&r.status==="WAITING_HUMAN");$("confirm-export").disabled=!(r.stage==="EXPORT"&&r.status==="WAITING_HUMAN");$("spec-json").value=r.spec?JSON.stringify(r.spec,null,2):"规格尚未生成";$("pdf-path").textContent=r.paths.pdf_inbox;$("allow-source").checked=r.request.approved_sources.includes("patsnap_web");$("allow-model").checked=r.request.approved_models.includes("codex");
const activeQueries=r.queries.filter(q=>q.status!=="superseded");
const queryStatuses={pending:"待执行",complete:"已完成",zero:"零命中",truncated:"未完整导出",failed:"失败",superseded:"已替代"};
$("queries").innerHTML=activeQueries.map(q=>`<div class="query"><strong>${esc(q.qid)}</strong><span class="pill">${esc(queryStatuses[q.status]||q.status)}</span><p>${esc(q.purpose||"旧版查询；请重编为普通检索式")}</p>${q.search_mode==="expert"?`<pre>${esc(q.query)}</pre><button class="secondary copy-query" data-query="${esc(q.qid)}">复制检索式</button>`:'<p class="warn">旧版计划保留历史，待执行内容请重编。</p>'}<small>结果总数：${esc(q.total_hits??"未登记")}；已导入：${esc(q.imported_unique??0)}</small></div>`).join("")||"计划完成后显示具体检索式。";
const history=r.queries.filter(q=>q.status==="superseded");if(history.length)$("queries").innerHTML+=`<details><summary>已替代的历史查询（${history.length} 条）</summary>${history.map(q=>`<p>${esc(q.qid)}：${esc(q.superseded_reason)}</p>`).join("")}</details>`;
document.querySelectorAll(".copy-query").forEach(b=>b.onclick=()=>perform(async()=>{await navigator.clipboard.writeText(activeQueries.find(q=>q.qid===b.dataset.query).query);message(`${b.dataset.query} 检索式已复制，请到智慧芽专家搜索执行。`);}));
$("query-id").innerHTML=activeQueries.map(q=>`<option value="${esc(q.qid)}">${esc(q.qid)} · ${esc(queryStatuses[q.status]||q.status)}</option>`).join("");
const pendingQuery=activeQueries.find(q=>!["complete","zero"].includes(q.status));if(pendingQuery)$("query-id").value=pendingQuery.qid;
$("query-id").onchange=()=>fillExecutionFields(true);$("import-form").status.onchange=()=>fillExecutionFields(false);fillExecutionFields(true);
$("replan").disabled=!r.spec||["DONE","STOPPED"].includes(r.status);
$("documents").innerHTML=Object.entries(r.records).map(([key,doc])=>{const pdf=r.documents[key],quality=pdf?.quality;return `<tr><td><b>${esc(key)}</b><small>${esc(doc.title||"标题待补充")}</small></td><td>${esc(r.results[key]?.class||"未分类")}<small>${esc((r.results[key]?.issues||[]).join("；"))}</small></td><td>${!pdf?"未取得":quality.complete?"全文已确认":quality.claims_complete?"权利要求已确认":quality.needs_ocr?"需 OCR":!quality.identity_verified?"号码待核实":"待确认完整性"}<small>${pdf?pdf.pages.length+" 页":""}</small></td><td>${pdf&&!quality.complete?`<button class="secondary confirm-document" data-key="${esc(key)}" data-pages="${pdf.pages.length}">确认已核对完整 PDF</button>`:"—"}</td></tr>`}).join("")||'<tr><td colspan="4">导入查询结果后，候选文献显示在这里。</td></tr>';
document.querySelectorAll(".confirm-document").forEach(b=>b.onclick=()=>perform(async()=>{const by=prompt("请填写确认人。确认前请核对全文未缺页、页数一致；本操作不代替阅读证据。");if(!by)return;const pages=Number(prompt("请输入已核对的 PDF 总页数",b.dataset.pages));if(!pages)return;await api("confirm_pdf",{key:b.dataset.key,by,pages,scope:r.spec.read_scope==="claims"||["全景","侵权风险"].includes(r.spec.intent)?"claims":"full"});await loadRun(r.run_id);message("已记录 PDF 完整性确认。");}));
$("pdf-reports").innerHTML=(r.pdf_reports||[]).map(x=>`<p class="warn">${esc(x.file||x.key)}：${esc(x.error||(x.quality?.issues||[]).join("；"))}</p>`).join("");$("trace").innerHTML=r.trace.slice().reverse().map(t=>`<p><small>${esc(t.at)}</small><br>${esc(t.action)}</p>`).join("");}
function fillExecutionFields(reset){const q=current?.queries.find(q=>q.qid===$("query-id").value);if(reset){$("actual-query").value=q?.actual_query||q?.query||"";$("total-hits").value=q?.total_hits??"";$("searched-at").value=q?.searched_at||"";}const successful=["complete","zero","truncated"].includes($("import-form").status.value);$("actual-query").required=q?.search_mode==="expert";$("total-hits").required=q?.search_mode==="expert"&&successful;}
async function refresh(){if(current)await loadRun(current.run_id);else await loadList();}
async function base64File(file){if(file.size>100*1024*1024)throw Error("文件不能超过 100 MB");return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=reject;reader.readAsDataURL(file);});}
$("create-form").onsubmit=e=>{e.preventDefault();perform(async()=>{const form=e.target;const v=Object.fromEntries(new FormData(form));const request={title:v.title,raw_input:v.raw_input,entry:v.entry,intent:v.entry==="lookup"?null:v.intent,read_scope:v.read_scope,keys:v.keys.split(/[，,\s]+/).filter(Boolean),budget_min:Number(v.budget_min),confidential:form.confidential.checked,approved_sources:form.approve_sources.checked?["patsnap_web"]:[],approved_models:form.approve_models.checked?["codex"]:[]};if(v.base_date)request.base_date=v.base_date;const r=await api("create",{request});await loadRun(r.run_id);message("任务已创建，进度会自动保存。");});};
$("new-run").onclick=()=>{current=null;$("create-view").hidden=false;$("run-view").hidden=true;$("page-title").textContent="从检索需求到原文证据";$("message").hidden=true;loadList();};$("refresh").onclick=()=>perform(refresh);
$("advance").onclick=()=>perform(async()=>{await api("advance");await refresh();message("已读取最新进度。");});
$("packet").onclick=()=>perform(async()=>{const packet=await api("packet");handoffText=`继续本项目专利检索任务 ${packet.run_id}。读取最新任务包 ${current.paths.agent_task}，按其中 skill 和 output_schema 完成 ${packet.stage}，将外层返回对象保存到 ${packet.result_path}，再执行 PowerShell 命令：\n${packet.submit_command}\n需要独立复核时使用独立子智能体上下文；原始PDF和程序配置不得改写。`;$("handoff").textContent=handoffText;$("handoff").hidden=false;$("copy-handoff").hidden=false;message("任务包已保存。请复制指令到 Codex 继续处理。");});
$("copy-handoff").onclick=()=>perform(async()=>{await navigator.clipboard.writeText(handoffText);message("已复制给 Codex 的指令。");});
$("copy-path").onclick=()=>perform(async()=>{await navigator.clipboard.writeText(current.paths.pdf_inbox);message("已复制 PDF 目录。");});
$("submit-agent").onclick=()=>perform(async()=>{await api("submit",{stage:current.stage,envelope:JSON.parse($("agent-json").value)});$("agent-json").value="";await refresh();message("已校验并保存 Agent 结果。");});
$("queries-save").onclick=()=>perform(async()=>{const result=await api("queries");await refresh();message("检索式与操作说明已保存：\n"+result.path);});
$("import-form").onsubmit=e=>{e.preventDefault();perform(async()=>{const form=e.target;const values=Object.fromEntries(new FormData(form));const execution={};if(values.actual_query.trim())execution.actual_query=values.actual_query.trim();if(values.total_hits!=="")execution.total_hits=Number(values.total_hits);if(values.searched_at)execution.searched_at=values.searched_at;const data={query:values.query,page:Number(values.page),status:values.status,note:values.note,execution};const file=form.file.files[0];if(file)await api("upload",{...data,name:file.name,base64:await base64File(file)});else await api("import",data);form.file.value="";await refresh();message("已保存此次查询结果。");});};
$("ingest").onclick=()=>perform(async()=>{await api("ingest_pdfs");await refresh();message("已读取 PDF 文件夹，请查看各文献的完整性状态。");});
$("pdf-upload").onchange=e=>perform(async()=>{for(const file of e.target.files)await api("upload",{name:file.name,base64:await base64File(file)});e.target.value="";await refresh();message("PDF 已放入任务文件夹并解析。");});
for(const gate of ["spec","export"]){$("confirm-"+gate).onclick=()=>perform(async()=>{await api("confirm",{gate,by:$("confirm-by").value});await refresh();message("已记录人工确认。");});}
$("export").onclick=()=>perform(async()=>{const result=await api("export");await refresh();message(`已导出：${result.status}\n报告：${result.report}\n证据：${result.evidence}`);});
$("update-spec").onclick=()=>perform(async()=>{await api("update_spec",{spec:JSON.parse($("spec-json").value),by:$("spec-by").value});await refresh();message("条件已更新，有效的已有材料将继续复用。");});
$("replan").onclick=()=>perform(async()=>{await api("replan",{reason:$("replan-reason").value,by:$("replan-by").value});await refresh();message("已保留历史查询，请生成 PLAN 任务交给 Codex 重编检索式。");});
$("authorize").onclick=()=>perform(async()=>{await api("authorize",{sources:$("allow-source").checked?["patsnap_web"]:[],models:$("allow-model").checked?["codex"]:[]});await refresh();message("已保存本任务授权范围。");});
$("stop").onclick=()=>perform(async()=>{await api("stop",{reason:$("stop-reason").value});await refresh();message("已停止新增工作，可抽检后交付部分结果。");});
document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b===button));for(const tab of ["work","documents","settings"])$("tab-"+tab).hidden=tab!==button.dataset.tab;});
perform(async()=>{const boot=await(await fetch("/api/bootstrap")).json();csrf=boot.csrf;$("data-dir").textContent=boot.data_dir;await loadList();});
